In [3]:
import pandas as pd

In [ ]:
import pandas as pd

def congruencial_mixto(semilla, a, c, m, n):
    """
    Genera una secuencia de números pseudoaleatorios utilizando el metodo congruencial mixto

    Args:
        semilla: La semilla inicial (un entero impar)
        a: El multiplicador (debe satisfacer las condiciones especificadas en el metodo)
        c: La constante aditiva (un entero impar)
        m: El mod (generalmente una potencia de 2)
        n: El número de números pseudoaleatorios a generar

    Returns:
        Un DataFrame con la secuencia de números pseudoaleatorios y sus atributos
    """
    if semilla % 2 == 0 or c % 2 == 0:
        print("Error: La semilla y la constante aditiva deben ser impares")
        return None
    if m <= 0 or n <= 0:
        print("Error: El mod y el numero de iteraciones deben ser positivos")
        return None

    # Inicializando las listas
    numeros_aleatorios = []
    r_i_minus_1 = []  # Para guardar ri-1
    x = semilla

    for i in range(n):
        if i > 0:
            r_i_minus_1.append(x)  # Guardar el valor anterior ri-1
        x = (a * x + c) % m
        numeros_aleatorios.append(x)

    # Agregar el primer valor de la semilla para ri-1
    r_i_minus_1.insert(0, semilla)

    # Crear DataFrame
    data = {
        'Iteracion [i]': range(1, n + 1),
        'ri-1': r_i_minus_1,
        'Multiplicador [a]': [a] * n,
        'Constante aditiva [c]': [c] * n,
        'r_{i+1}': numeros_aleatorios
    }

    df = pd.DataFrame(data)
    # Para obtener pseudoaleatorios entre 0 y 1
    df['ui'] = df['r_{i+1}'] / m

    return df

semilla = 48643
a = 65537
c = 11
m = 2**31  # 2147483648
n = 100    #  elementos de aleatorios a generar

# Generar pseudoaleatorios
df = congruencial_mixto(semilla, a, c, m, n)

In [35]:
df

,Iteracion [i],ri-1,Multiplicador [a],Constante aditiva [c],r_{i+1},ui
0,1,48643,65537,11,1040432654,0.484489
1,2,1040432654,65537,11,2081537561,0.969291
2,3,2081537561,65537,11,975879716,0.454429
3,4,975879716,65537,11,2018426415,0.939903
4,5,2018426415,65537,11,914210362,0.425712
...,...,...,...,...,...,...
95,96,1123598872,65537,11,84984355,0.039574
96,97,84984355,65537,11,1194574382,0.556267
97,98,1194574382,65537,11,157401657,0.073296
98,99,157401657,65537,11,1268433476,0.590660
99,100,1268433476,65537,11,232702543,0.108361