# Primero, escribir con orden, no mal redactado

#### Realiza un analisis exploratorio de datos del archivo: "Motor_Vehicle_Collisions.csv", realiza una estadistica descriptiva del archivo, homologa si es necesario las variables, define cuales son continuas y cuales discretas, haz una limpieza en los datos que sea necesario, normaliza las variables discretas y discretiza las variables continuas, así como crea una base entidad-relación y haz una consulta entre tablas con lenguaje sql (recomendada la libreria "pandasql"). Finalmente el código con el que trabajaste envialo a:
---
# Se debe realizar (con la data anexada en el csv):

* De ser necesario una limpiesa de datos
* Analisis exploratorio de datos
* Estadistica descriptivas 
* Normalización de variables discretas
* Discretización de variables continuas
* Crear una base entidad-relación
* Realizar una consulta entre tablas con lenguaje sql (recomendada la libreria "pandasql") a mi crieterio es mejor .query() si solo se va consumir una BD y se es crear mejor usar lietral sql, bdeaver, se puede usar pandasql, pero no es necesario, se puede hacer con pandas y numpy pero bueno aqui puedes mencinarlo ya que se ocupa menos recurso tal vez

---
Solo pondria esos puntos a partir de aqui es como yo entregaria la prueba tecnica al ser jr, le bajare el nivel es decir no entregare una clase documentada o consumida en un proceso automatizado

# Limpieza de datos

In [44]:
import pandas as pd

# ver todas las columnas de un dataframe
pd.set_option('display.max_columns', None)

In [45]:
# yo lo gaurdaria y sin perder datos lo convertitia en .parquet es mas optimo, pero seguire en csv
df = pd.read_csv("C:/Users/oscar/Downloads/Motor_Vehicle_Collisions.csv")

C:\Users\oscar\AppData\Local\Temp\ipykernel_25584\565568521.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/oscar/Downloads/Motor_Vehicle_Collisions.csv")

In [46]:
# colcoar el nom bre de las columnas con guines bajo y mayausculas todo (Es buena practica que las columans se llamen asi) se le conoce como estandarizacion
# si en algun punto esta data la puede usar alguien mas o un dash, o ingestar ya se tiene homologada UNA sola columnas para eso 
df.columns = df.columns.str.replace(' ', '_').str.upper()

In [48]:
df

,CRASH_DATE,CRASH_TIME,BOROUGH,ZIP_CODE,LATITUDE,LONGITUDE,LOCATION,ON_STREET_NAME,CROSS_STREET_NAME,OFF_STREET_NAME,NUMBER_OF_PERSONS_INJURED,NUMBER_OF_PERSONS_KILLED,NUMBER_OF_PEDESTRIANS_INJURED,NUMBER_OF_PEDESTRIANS_KILLED,NUMBER_OF_CYCLIST_INJURED,NUMBER_OF_CYCLIST_KILLED,NUMBER_OF_MOTORIST_INJURED,NUMBER_OF_MOTORIST_KILLED,CONTRIBUTING_FACTOR_VEHICLE_1,CONTRIBUTING_FACTOR_VEHICLE_2,CONTRIBUTING_FACTOR_VEHICLE_3,CONTRIBUTING_FACTOR_VEHICLE_4,CONTRIBUTING_FACTOR_VEHICLE_5,COLLISION_ID,VEHICLE_TYPE_CODE_1,VEHICLE_TYPE_CODE_2,VEHICLE_TYPE_CODE_3,VEHICLE_TYPE_CODE_4,VEHICLE_TYPE_CODE_5
0,09/11/2021,2:39,NaN,NaN,NaN,NaN,NaN,WHITESTONE EXPRESSWAY,20 AVENUE,NaN,2.0,0.0,0,0,0,0,2,0,Aggressive Driving/Road Rage,Unspecified,NaN,NaN,NaN,4455765,Sedan,Sedan,NaN,NaN,NaN
1,03/26/2022,11:45,NaN,NaN,NaN,NaN,NaN,QUEENSBORO BRIDGE UPPER,NaN,NaN,1.0,0.0,0,0,0,0,1,0,Pavement Slippery,NaN,NaN,NaN,NaN,4513547,Sedan,NaN,NaN,NaN,NaN
2,06/29/2022,6:55,NaN,NaN,NaN,NaN,NaN,THROGS NECK BRIDGE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4541903,Sedan,Pick-up Truck,NaN,NaN,NaN
3,09/11/2021,9:35,BROOKLYN,11208.0,40.667202,-73.866500,"(40.667202, -73.8665)",NaN,NaN,1211 LORING AVENUE,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4456314,Sedan,NaN,NaN,NaN,NaN
4,12/14/2021,8:13,BROOKLYN,11233.0,40.683304,-73.917274,"(40.683304, -73.917274)",SARATOGA AVENUE,DECATUR STREET,NaN,0.0,0.0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,4486609,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034014,07/03/2023,18:05,NaN,NaN,40.866806,-73.931010,"(40.866806, -73.93101)",RIVERSIDE DRIVE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Turning Improperly,Unspecified,NaN,NaN,NaN,4648110,Sedan,Sedan,NaN,NaN,NaN
2034015,07/22/2023,21:39,BRONX,10457.0,40.844177,-73.902920,"(40.844177, -73.90292)",EAST 174 STREET,WEBSTER AVENUE,NaN,1.0,0.0,1,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4648117,Sedan,NaN,NaN,NaN,NaN
2034016,07/02/2023,17:55,MANHATTAN,10006.0,40.711033,-74.014540,"(40.711033, -74.01454)",WEST STREET,LIBERTY STREET,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,4648366,Taxi,NaN,NaN,NaN,NaN
2034017,07/22/2023,13:15,QUEENS,11433.0,40.691580,-73.793190,"(40.69158, -73.79319)",110 AVENUE,157 STREET,NaN,1.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4648129,Station Wagon/Sport Utility Vehicle,E-Bike,NaN,NaN,NaN
2034018,07/22/2023,3:00,QUEENS,11433.0,40.700240,-73.792854,"(40.70024, -73.792854)",SOUTH ROAD,164 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4647913,Sedan,NaN,NaN,NaN,NaN

In [50]:
df.query("CRASH_DATE != CRASH_DATE") # No hay fechs vacias, eso es bueno

Empty DataFrame
Columns: [CRASH_DATE, CRASH_TIME, BOROUGH, ZIP_CODE, LATITUDE, LONGITUDE, LOCATION, ON_STREET_NAME, CROSS_STREET_NAME, OFF_STREET_NAME, NUMBER_OF_PERSONS_INJURED, NUMBER_OF_PERSONS_KILLED, NUMBER_OF_PEDESTRIANS_INJURED, NUMBER_OF_PEDESTRIANS_KILLED, NUMBER_OF_CYCLIST_INJURED, NUMBER_OF_CYCLIST_KILLED, NUMBER_OF_MOTORIST_INJURED, NUMBER_OF_MOTORIST_KILLED, CONTRIBUTING_FACTOR_VEHICLE_1, CONTRIBUTING_FACTOR_VEHICLE_2, CONTRIBUTING_FACTOR_VEHICLE_3, CONTRIBUTING_FACTOR_VEHICLE_4, CONTRIBUTING_FACTOR_VEHICLE_5, COLLISION_ID, VEHICLE_TYPE_CODE_1, VEHICLE_TYPE_CODE_2, VEHICLE_TYPE_CODE_3, VEHICLE_TYPE_CODE_4, VEHICLE_TYPE_CODE_5]
Index: []

In [51]:
df

,CRASH_DATE,CRASH_TIME,BOROUGH,ZIP_CODE,LATITUDE,LONGITUDE,LOCATION,ON_STREET_NAME,CROSS_STREET_NAME,OFF_STREET_NAME,NUMBER_OF_PERSONS_INJURED,NUMBER_OF_PERSONS_KILLED,NUMBER_OF_PEDESTRIANS_INJURED,NUMBER_OF_PEDESTRIANS_KILLED,NUMBER_OF_CYCLIST_INJURED,NUMBER_OF_CYCLIST_KILLED,NUMBER_OF_MOTORIST_INJURED,NUMBER_OF_MOTORIST_KILLED,CONTRIBUTING_FACTOR_VEHICLE_1,CONTRIBUTING_FACTOR_VEHICLE_2,CONTRIBUTING_FACTOR_VEHICLE_3,CONTRIBUTING_FACTOR_VEHICLE_4,CONTRIBUTING_FACTOR_VEHICLE_5,COLLISION_ID,VEHICLE_TYPE_CODE_1,VEHICLE_TYPE_CODE_2,VEHICLE_TYPE_CODE_3,VEHICLE_TYPE_CODE_4,VEHICLE_TYPE_CODE_5
0,09/11/2021,2:39,NaN,NaN,NaN,NaN,NaN,WHITESTONE EXPRESSWAY,20 AVENUE,NaN,2.0,0.0,0,0,0,0,2,0,Aggressive Driving/Road Rage,Unspecified,NaN,NaN,NaN,4455765,Sedan,Sedan,NaN,NaN,NaN
1,03/26/2022,11:45,NaN,NaN,NaN,NaN,NaN,QUEENSBORO BRIDGE UPPER,NaN,NaN,1.0,0.0,0,0,0,0,1,0,Pavement Slippery,NaN,NaN,NaN,NaN,4513547,Sedan,NaN,NaN,NaN,NaN
2,06/29/2022,6:55,NaN,NaN,NaN,NaN,NaN,THROGS NECK BRIDGE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4541903,Sedan,Pick-up Truck,NaN,NaN,NaN
3,09/11/2021,9:35,BROOKLYN,11208.0,40.667202,-73.866500,"(40.667202, -73.8665)",NaN,NaN,1211 LORING AVENUE,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4456314,Sedan,NaN,NaN,NaN,NaN
4,12/14/2021,8:13,BROOKLYN,11233.0,40.683304,-73.917274,"(40.683304, -73.917274)",SARATOGA AVENUE,DECATUR STREET,NaN,0.0,0.0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,4486609,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034014,07/03/2023,18:05,NaN,NaN,40.866806,-73.931010,"(40.866806, -73.93101)",RIVERSIDE DRIVE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Turning Improperly,Unspecified,NaN,NaN,NaN,4648110,Sedan,Sedan,NaN,NaN,NaN
2034015,07/22/2023,21:39,BRONX,10457.0,40.844177,-73.902920,"(40.844177, -73.90292)",EAST 174 STREET,WEBSTER AVENUE,NaN,1.0,0.0,1,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4648117,Sedan,NaN,NaN,NaN,NaN
2034016,07/02/2023,17:55,MANHATTAN,10006.0,40.711033,-74.014540,"(40.711033, -74.01454)",WEST STREET,LIBERTY STREET,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,4648366,Taxi,NaN,NaN,NaN,NaN
2034017,07/22/2023,13:15,QUEENS,11433.0,40.691580,-73.793190,"(40.69158, -73.79319)",110 AVENUE,157 STREET,NaN,1.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4648129,Station Wagon/Sport Utility Vehicle,E-Bike,NaN,NaN,NaN
2034018,07/22/2023,3:00,QUEENS,11433.0,40.700240,-73.792854,"(40.70024, -73.792854)",SOUTH ROAD,164 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4647913,Sedan,NaN,NaN,NaN,NaN

Podemos notar que el archivo "Motor_Vehicle_Collisions.csv" contiene información sobre accidentes de tráfico en la ciudad de Nueva York, por brooklyn y el BRONX sabemos esto 
de los que teenmos mapeados son 5 distritos, existen vacios en la columna de distritos, por lo que se debe hacer una limpieza de datos, para poder realizar un análisis exploratorio de datos si es posible recuperarlos con la msima data, que claro igual podemos bsucar en git hub un catalogo de dicha locacion en calle

Riesgo de hacer eso es que podemos agregar sesgo si estan mal el catlogo

Beneficio, perdemos cesgo tendriamos mejores metricas

In [46]:
df['BOROUGH'].value_counts()

BOROUGH
BROOKLYN         444936
QUEENS           375361
MANHATTAN        315278
BRONX            206913
STATEN ISLAND     58744
Name: count, dtype: int64

Podemos limpiar al menos BOROUGH, en que sentido? peude que no tengamso una lat y long pero si su dsitrito, se remplazarian los valores vacios por los valores de distrito y asi si hacemos metricas refentes a los distritos disminuriamos vacios

In [59]:
df.query("ON_STREET_NAME == 'PITKIN AVENUE'") # Filtrar por Queens

,CRASH_DATE,CRASH_TIME,BOROUGH,ZIP_CODE,LATITUDE,LONGITUDE,LOCATION,ON_STREET_NAME,CROSS_STREET_NAME,OFF_STREET_NAME,NUMBER_OF_PERSONS_INJURED,NUMBER_OF_PERSONS_KILLED,NUMBER_OF_PEDESTRIANS_INJURED,NUMBER_OF_PEDESTRIANS_KILLED,NUMBER_OF_CYCLIST_INJURED,NUMBER_OF_CYCLIST_KILLED,NUMBER_OF_MOTORIST_INJURED,NUMBER_OF_MOTORIST_KILLED,CONTRIBUTING_FACTOR_VEHICLE_1,CONTRIBUTING_FACTOR_VEHICLE_2,CONTRIBUTING_FACTOR_VEHICLE_3,CONTRIBUTING_FACTOR_VEHICLE_4,CONTRIBUTING_FACTOR_VEHICLE_5,COLLISION_ID,VEHICLE_TYPE_CODE_1,VEHICLE_TYPE_CODE_2,VEHICLE_TYPE_CODE_3,VEHICLE_TYPE_CODE_4,VEHICLE_TYPE_CODE_5
389,09/10/2021,13:10,BROOKLYN,11212.0,40.668430,-73.919190,"(40.66843, -73.91919)",PITKIN AVENUE,GRAFTON STREET,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,4456810,Sedan,E-Bike,NaN,NaN,NaN
890,04/14/2021,13:06,BROOKLYN,11212.0,40.669823,-73.909810,"(40.669823, -73.90981)",PITKIN AVENUE,THATFORD AVENUE,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4407570,Sedan,NaN,NaN,NaN,NaN
1342,09/11/2021,18:30,BROOKLYN,11212.0,40.669403,-73.912605,"(40.669403, -73.912605)",PITKIN AVENUE,BRISTOL STREET,NaN,0.0,0.0,0,0,0,0,0,0,Passing or Lane Usage Improper,Unspecified,NaN,NaN,NaN,4455909,Bus,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2009,03/26/2022,11:00,NaN,NaN,40.674786,-73.876200,"(40.674786, -73.8762)",PITKIN AVENUE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,Unspecified,NaN,NaN,4513840,Sedan,Sedan,Sedan,NaN,NaN
2171,04/17/2021,0:01,NaN,NaN,40.675297,-73.872680,"(40.675297, -73.87268)",PITKIN AVENUE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Passing Too Closely,Unspecified,NaN,NaN,NaN,4408818,Sedan,Sedan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028278,07/01/2023,3:05,BROOKLYN,11208.0,40.675297,-73.872680,"(40.675297, -73.87268)",PITKIN AVENUE,DOSCHER STREET,NaN,2.0,0.0,0,0,0,0,2,0,Other Vehicular,Other Vehicular,NaN,NaN,NaN,4642103,Sedan,Motorscooter,NaN,NaN,NaN
2029191,07/05/2023,14:04,QUEENS,11417.0,40.676617,-73.857900,"(40.676617, -73.8579)",PITKIN AVENUE,79 STREET,NaN,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Traffic Control Disregarded,NaN,NaN,NaN,4642922,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2029377,07/07/2023,7:54,BROOKLYN,11208.0,40.675804,-73.869156,"(40.675804, -73.869156)",PITKIN AVENUE,HEMLOCK STREET,NaN,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Driver Inattention/Distraction,NaN,NaN,NaN,4643818,Sedan,Sedan,NaN,NaN,NaN
2031167,07/13/2023,21:40,BROOKLYN,11208.0,40.673860,-73.882590,"(40.67386, -73.88259)",PITKIN AVENUE,LINWOOD STREET,NaN,2.0,0.0,0,0,0,0,2,0,Unspecified,Unspecified,NaN,NaN,NaN,4645573,Station Wagon/Sport Utility Vehicle,Motorscooter,NaN,NaN,NaN
2031981,07/12/2023,6:43,BROOKLYN,11212.0,40.670790,-73.903275,"(40.67079, -73.903275)",PITKIN AVENUE,JUNIUS STREET,NaN,1.0,0.0,0,0,0,0,1,0,Unspecified,Unspecified,NaN,NaN,NaN,4645775,Sedan,Bus,NaN,NaN,NaN

In [60]:
df

,CRASH_DATE,CRASH_TIME,BOROUGH,ZIP_CODE,LATITUDE,LONGITUDE,LOCATION,ON_STREET_NAME,CROSS_STREET_NAME,OFF_STREET_NAME,NUMBER_OF_PERSONS_INJURED,NUMBER_OF_PERSONS_KILLED,NUMBER_OF_PEDESTRIANS_INJURED,NUMBER_OF_PEDESTRIANS_KILLED,NUMBER_OF_CYCLIST_INJURED,NUMBER_OF_CYCLIST_KILLED,NUMBER_OF_MOTORIST_INJURED,NUMBER_OF_MOTORIST_KILLED,CONTRIBUTING_FACTOR_VEHICLE_1,CONTRIBUTING_FACTOR_VEHICLE_2,CONTRIBUTING_FACTOR_VEHICLE_3,CONTRIBUTING_FACTOR_VEHICLE_4,CONTRIBUTING_FACTOR_VEHICLE_5,COLLISION_ID,VEHICLE_TYPE_CODE_1,VEHICLE_TYPE_CODE_2,VEHICLE_TYPE_CODE_3,VEHICLE_TYPE_CODE_4,VEHICLE_TYPE_CODE_5
0,09/11/2021,2:39,NaN,NaN,NaN,NaN,NaN,WHITESTONE EXPRESSWAY,20 AVENUE,NaN,2.0,0.0,0,0,0,0,2,0,Aggressive Driving/Road Rage,Unspecified,NaN,NaN,NaN,4455765,Sedan,Sedan,NaN,NaN,NaN
1,03/26/2022,11:45,NaN,NaN,NaN,NaN,NaN,QUEENSBORO BRIDGE UPPER,NaN,NaN,1.0,0.0,0,0,0,0,1,0,Pavement Slippery,NaN,NaN,NaN,NaN,4513547,Sedan,NaN,NaN,NaN,NaN
2,06/29/2022,6:55,NaN,NaN,NaN,NaN,NaN,THROGS NECK BRIDGE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Following Too Closely,Unspecified,NaN,NaN,NaN,4541903,Sedan,Pick-up Truck,NaN,NaN,NaN
3,09/11/2021,9:35,BROOKLYN,11208.0,40.667202,-73.866500,"(40.667202, -73.8665)",NaN,NaN,1211 LORING AVENUE,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4456314,Sedan,NaN,NaN,NaN,NaN
4,12/14/2021,8:13,BROOKLYN,11233.0,40.683304,-73.917274,"(40.683304, -73.917274)",SARATOGA AVENUE,DECATUR STREET,NaN,0.0,0.0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,4486609,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034014,07/03/2023,18:05,NaN,NaN,40.866806,-73.931010,"(40.866806, -73.93101)",RIVERSIDE DRIVE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Turning Improperly,Unspecified,NaN,NaN,NaN,4648110,Sedan,Sedan,NaN,NaN,NaN
2034015,07/22/2023,21:39,BRONX,10457.0,40.844177,-73.902920,"(40.844177, -73.90292)",EAST 174 STREET,WEBSTER AVENUE,NaN,1.0,0.0,1,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4648117,Sedan,NaN,NaN,NaN,NaN
2034016,07/02/2023,17:55,MANHATTAN,10006.0,40.711033,-74.014540,"(40.711033, -74.01454)",WEST STREET,LIBERTY STREET,NaN,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,4648366,Taxi,NaN,NaN,NaN,NaN
2034017,07/22/2023,13:15,QUEENS,11433.0,40.691580,-73.793190,"(40.69158, -73.79319)",110 AVENUE,157 STREET,NaN,1.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,4648129,Station Wagon/Sport Utility Vehicle,E-Bike,NaN,NaN,NaN
2034018,07/22/2023,3:00,QUEENS,11433.0,40.700240,-73.792854,"(40.70024, -73.792854)",SOUTH ROAD,164 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4647913,Sedan,NaN,NaN,NaN,NaN

In [17]:
import numpy as np
import pandas as pd

# Autor: Equipo 3

def generar_dataframe():
    """ Función para generar un DataFrame con 100 filas y las siguientes columnas:
    - U1: 100 valores aleatorios entre 0 y 1 (por la indicacion de que sea uniforme (0,1))
    - U2: 100 valores aleatorios entre 0 y 1
    - V1: 2 * U1 - 1
    - V2: 2 * U2 - 2
    - S: raíz cuadrada de V1^2 + V2^2
    - Decision: 1 si S > 1, 0 en otro caso
    - x: 0 si S <= 0, V1 * sqrt(-2 * log(S) / S) en otro caso
    - y: 0 si S <= 0, V2 * sqrt(-2 * log(S) / S) en otro caso
    
    Parametros:
        None
    Returns:
        pd.DataFrame: DataFrame con las columnas 'U1', 'U2', 'V1', 'V2', 'S', 'Decision', 'x', 'y'
    """

    U1 = np.random.uniform(0, 1, 100)
    U2 = np.random.uniform(0, 1, 100)
    
    V1 = 2 * U1 - 1
    V2 = 2 * U2 - 2
    
    S = np.sqrt(V1**2 + V2**2)
    
    Decision = np.where(S > 1, 1, 0)
    
    # Evitar valores invalidos en logaritmo y división para la desicion ya que cuando sea 0 los tomara como NaN
    valid_mask = (S > 0) & (S <= 1)
    
    x = np.zeros_like(S)
    y = np.zeros_like(S)
    
    x[valid_mask] = V1[valid_mask] * np.sqrt(-2 * np.log(S[valid_mask]) / S[valid_mask])
    y[valid_mask] = V2[valid_mask] * np.sqrt(-2 * np.log(S[valid_mask]) / S[valid_mask])
    
    df = pd.DataFrame({
        'U1': U1,
        'U2': U2,
        'V1': V1,
        'V2': V2,
        'S': S,
        'Decision': Decision,
        'x': x,
        'y': y
    })
    
    return df

# Generar y mostrar el DataFrame
df = generar_dataframe()
df.to_excel("C:/Users/oscar/Downloads/Practica_12.xlsx", index=False)

In [19]:
df.to_excel("C:/Users/oscar/Downloads/Practica_12.xlsx", index=False)